# Generated by Django 3.2.4 on 2021-10-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210629_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('age', models.IntegerField(max_length=3, verbose_name='Idade')),
                ('hobby', models.CharField(max_length=255, verbose_name='Hobby')),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            bases=('core.base',),
        ),
        migrations.RemoveField(
            model_name='client',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
