# Generated by Django 3.2.4 on 2021-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211025_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
